### ISSUE TITLE
Need to get an RC staged by Dec 15.

### ISSUE THREAD

**Issue by starksm64** [eclipse-ee4j/cdi#575]
We need to put together a full release candidate that I can then stage for review by the specification project by Dec 15 for inclusion in EE10. Please link to whatever tasks are needed for that and feel free to assign any to me.

**Comment by manovotn** [comment]
Here is what I know we need to do.

CDI spec:
* Move `BeanContainer` method under `BeanManager`, see https://github.com/eclipse-ee4j/cdi/issues/568
* Allow OM to access declaring class via CDI API, see https://github.com/eclipse-ee4j/cdi/issues/563
* Specify invalid treatment of `@Enhancement` and `@Registration` phases, see https://github.com/eclipse-ee4j/cdi/pull/576
* Move `@SessionScoped` into CDI Full as this is poorly
  * No issue ATM @Ladicek works on this as we speak


TCKs:
* Some tests are not under appropriate package https://github.com/eclipse-ee4j/cdi-tck/issues/320 
* Adjust `CustomStereotypeTest`, see https://github.com/eclipse-ee4j/cdi-tck/pull/323
* Provide tests for negative scenarios when using Build compatible extensions, see https://github.com/eclipse-ee4j/cdi-tck/issues/321
* Add tests for `withSubtypes` and `withAnnotations`, see https://github.com/eclipse-ee4j/cdi-tck/pull/322
* Check whether tests with `@SessionScope` are under "Full" category
  * Issue not created yet

These issues are already being worked on by either me or @Ladicek and I guess we'll be able to address them pretty fast.

**Comment by Ladicek** [comment]
@manovotn thanks, I wanted to put down a similar list myself :-) Can you make each item a TODO item? It's enough to put `[ ]` after the bullet point. For example, this:

```md
- [ ] my TODO item
- [ ] my other TODO item
```

results in:

- [ ] my TODO item
- [ ] my other TODO item

**Comment by manovotn** [comment]
@Ladicek, I was going to do it once I had all the issues.
Updated with checkboxes and updated with additional issues.

**Comment by Ladicek** [comment]
Perfect, thanks!

**Comment by manovotn** [comment]
Correct me if I am wrong @Ladicek but I think we have everything done except for merge of https://github.com/eclipse-ee4j/cdi-tck/pull/328 which requires new CDI API version anyway :-)

**Comment by Ladicek** [comment]
How about we do a 4.0.0.Beta3 so that we can get the PR done and merged? :-)

**Comment by Ladicek** [comment]
In other words, yea I agree, we should be ready for RC.

**Comment by manovotn** [comment]
> How about we do a 4.0.0.Beta3 so that we can get the PR done and merged? :-)

Did you just volunteer? :D

**Comment by Ladicek** [comment]
> > How about we do a 4.0.0.Beta3 so that we can get the PR done and merged? :-)
> 
> Did you just volunteer? :D

I'm on it!

**Comment by Ladicek** [comment]
Aaaand done, Beta3 should be on its way to Central.

**Comment by manovotn** [comment]
@starksm64 all the tasks that I was aware of are now completed.

**Comment by starksm64** [comment]
Ok, I'll start on an RC. Is there an updated Weld release that should be used in the TCK distribution?

**Comment by manovotn** [comment]
@starksm64 mmm, not for the latest version. There is Alpha1, but that doesn't implement latest of changes.
If you need that, I can have it within a day or two - it's exactly what I'm going to work on starting tomorrow.

**Comment by starksm64** [comment]
Ok, I'll get started but wait on putting out the release until the new Weld version is out.

**Comment by manovotn** [comment]
@starksm64 I have just released new Weld version that implements latest CDI and CDI TCK (4.0.0.Alpha5 which I also released). Expect it to land in Central within an hour.

Weld core - 5.0.0.Alpha2
Weld API - 5.0.Beta4

The above version passes all TCK when ran against embedded container.

**Comment by starksm64** [comment]
Ok, thanks.

**Comment by manovotn** [comment]
@graemerocher Ladislav is on PTO.

I dont this `@Registration` supported it at any point.
And looking at javadoc, I don't think it needs to. To quote a bit of it:
```
 * If a {@code @Registration} method has a parameter of type {@code BeanInfo}, the method is called once
 * for each bean whose set of bean types contains at least one <em>expected type</em>.
```

I.e. it already goes through all types of any bean to notify the method so it should cover the same case you are looking for.
Or am I missing something?

**Comment by graemerocher** [comment]
ok gotcha

**Comment by starksm64** [comment]
So I have 4.0.0-RC1 version of cdi-api and cdi-tck staged. I tried running the latest weld core code against these using a staging repo profile, and I'm seeing the following errors:

```
[ERROR] Tests run: 1254, Failures: 14, Errors: 0, Skipped: 6, Time elapsed: 47.415 s <<< FAILURE! - in TestSuite
[ERROR] org.jboss.cdi.tck.tests.definition.stereotype.priority.inherited.StereotypeInheritedPriorityTest.testPriorityWasInherited  Time elapsed: 0.01 s  <<< FAILURE!
java.lang.AssertionError: expected [true] but found [false]
        at org.jboss.cdi.tck.tests.definition.stereotype.priority.inherited.StereotypeInheritedPriorityTest.testPriorityWasInherited(StereotypeInheritedPriorityTest.java:31)

[ERROR] org.jboss.cdi.tck.tests.definition.stereotype.priority.StereotypeWithPriorityTest.testBeanPriorityFromStereotypeOverridesOtherAlternative  Time elapsed: 0.002 s  <<< FAILURE!
java.lang.AssertionError: expected [BazAlternative2] but found [BazAlternative]
        at org.jboss.cdi.tck.tests.definition.stereotype.priority.StereotypeWithPriorityTest.testBeanPriorityFromStereotypeOverridesOtherAlternative(StereotypeWithPriorityTest.java:54)

[ERROR] org.jboss.cdi.tck.tests.definition.stereotype.priority.StereotypeWithPriorityTest.testStereotypeWithAlternativeAndPriority  Time elapsed: 0.002 s  <<< FAILURE!
java.lang.AssertionError: expected [BarExtended] but found [Bar]
        at org.jboss.cdi.tck.tests.definition.stereotype.priority.StereotypeWithPriorityTest.testStereotypeWithAlternativeAndPriority(StereotypeWithPriorityTest.java:47)

[ERROR] org.jboss.cdi.tck.tests.definition.stereotype.priority.StereotypeWithPriorityTest.testStereotypeWithPriority  Time elapsed: 0.002 s  <<< FAILURE!
java.lang.AssertionError: expected [FooAlternative] but found [Foo]
        at org.jboss.cdi.tck.tests.definition.stereotype.priority.StereotypeWithPriorityTest.testStereotypeWithPriority(StereotypeWithPriorityTest.java:40)

[ERROR] org.jboss.cdi.tck.tests.definition.stereotype.broken.multiplePriorities.inherited.StereotypeInheritedPriorityConflictTest.arquillianBeforeClass  Time elapsed: 0.075 s  <<< FAILURE!
java.lang.RuntimeException: Expected exception of type jakarta.enterprise.inject.spi.DefinitionException during deployment of _DEFAULT_, but no exception was thrown.

[ERROR] org.jboss.cdi.tck.tests.definition.stereotype.broken.multiplePriorities.ConflictingPrioritiesFromSingleStereotypeTest.arquillianBeforeClass  Time elapsed: 0.077 s  <<< FAILURE!
java.lang.RuntimeException: Expected exception of type jakarta.enterprise.inject.spi.DefinitionException during deployment of _DEFAULT_, but no exception was thrown.

[ERROR] org.jboss.cdi.tck.tests.definition.stereotype.broken.multiplePriorities.ConflictingPriorityStereotypesTest.arquillianBeforeClass  Time elapsed: 0.07 s  <<< FAILURE!
java.lang.RuntimeException: Expected exception of type jakarta.enterprise.inject.spi.DefinitionException during deployment of _DEFAULT_, but no exception was thrown.

[ERROR] org.jboss.cdi.tck.tests.event.observer.method.ObserverMethodTest.testGetDeclaringBeanOnObserverMethod  Time elapsed: 0.002 s  <<< FAILURE!
java.lang.AssertionError: expected object to not be null
        at org.jboss.cdi.tck.tests.event.observer.method.ObserverMethodTest.testGetDeclaringBeanOnObserverMethod(ObserverMethodTest.java:71)

[ERROR] org.jboss.cdi.tck.tests.lookup.dynamic.handle.InstanceHandleTest.testGetAfterDestroyingContextualInstance  Time elapsed: 0.002 s  <<< FAILURE!
java.lang.AbstractMethodError: Receiver class org.jboss.weld.bean.builtin.InstanceImpl does not define or inherit an implementation of the resolved method abstract getHandle()Ljakarta/enterprise/inject/Instance$Handle; of interface jakarta.enterprise.inject.Instance.
        at org.jboss.cdi.tck.tests.lookup.dynamic.handle.InstanceHandleTest.testGetAfterDestroyingContextualInstance(InstanceHandleTest.java:96)

[ERROR] org.jboss.cdi.tck.tests.lookup.dynamic.handle.InstanceHandleTest.testGetHandle  Time elapsed: 0.002 s  <<< FAILURE!
java.lang.AbstractMethodError: Receiver class org.jboss.weld.bean.builtin.InstanceImpl does not define or inherit an implementation of the resolved method abstract getHandle()Ljakarta/enterprise/inject/Instance$Handle; of interface jakarta.enterprise.inject.Instance.
        at org.jboss.cdi.tck.tests.lookup.dynamic.handle.InstanceHandleTest.testGetHandle(InstanceHandleTest.java:54)

[ERROR] org.jboss.cdi.tck.tests.lookup.dynamic.handle.InstanceHandleTest.testHandles  Time elapsed: 0.002 s  <<< FAILURE!
java.lang.AbstractMethodError: Receiver class org.jboss.weld.bean.builtin.InstanceImpl does not define or inherit an implementation of the resolved method abstract handles()Ljava/lang/Iterable; of interface jakarta.enterprise.inject.Instance.
        at org.jboss.cdi.tck.tests.lookup.dynamic.handle.InstanceHandleTest.testHandles(InstanceHandleTest.java:120)

[ERROR] org.jboss.cdi.tck.tests.build.compatible.extensions.syntheticBean.SyntheticBeanTest.test  Time elapsed: 0.001 s  <<< FAILURE!
java.lang.AbstractMethodError: Receiver class org.jboss.weld.bean.builtin.InstanceImpl does not define or inherit an implementation of the resolved method abstract getHandle()Ljakarta/enterprise/inject/Instance$Handle; of interface jakarta.enterprise.inject.Instance.
        at org.jboss.cdi.tck.tests.build.compatible.extensions.syntheticBean.SyntheticBeanTest.test(SyntheticBeanTest.java:30)

[ERROR] org.jboss.cdi.tck.tests.build.compatible.extensions.syntheticBeanWithLookup.SyntheticBeanWithLookupTest.test  Time elapsed: 0.002 s  <<< FAILURE!
java.lang.AbstractMethodError: Receiver class org.jboss.weld.bean.builtin.InstanceImpl does not define or inherit an implementation of the resolved method abstract getHandle()Ljakarta/enterprise/inject/Instance$Handle; of interface jakarta.enterprise.inject.Instance.
        at org.jboss.cdi.tck.tests.build.compatible.extensions.syntheticBeanWithLookup.SyntheticBeanWithLookupTest.test(SyntheticBeanWithLookupTest.java:37)

[ERROR] org.jboss.cdi.tck.tests.build.compatible.extensions.syntheticBeanInjectionPoint.SyntheticBeanInjectionPointTest.test  Time elapsed: 0.001 s  <<< FAILURE!
java.lang.AbstractMethodError: Receiver class org.jboss.weld.bean.builtin.InstanceImpl does not define or inherit an implementation of the resolved method abstract getHandle()Ljakarta/enterprise/inject/Instance$Handle; of interface jakarta.enterprise.inject.Instance.
        at org.jboss.cdi.tck.tests.build.compatible.extensions.syntheticBeanInjectionPoint.SyntheticBeanInjectionPointTest.test(SyntheticBeanInjectionPointTest.java:39)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   SyntheticBeanTest>Arquillian.run:138->test:30 AbstractMethod Receiver class or...
[ERROR]   SyntheticBeanInjectionPointTest>Arquillian.run:138->test:39 AbstractMethod Rec...
[ERROR]   SyntheticBeanWithLookupTest>Arquillian.run:138->test:37 AbstractMethod Receive...
[ERROR]   ConflictingPrioritiesFromSingleStereotypeTest>Arquillian.arquillianBeforeClass:99 » Runtime
[ERROR]   ConflictingPriorityStereotypesTest>Arquillian.arquillianBeforeClass:99 » Runtime
[ERROR]   StereotypeInheritedPriorityConflictTest>Arquillian.arquillianBeforeClass:99 » Runtime
[ERROR]   StereotypeWithPriorityTest>Arquillian.run:138->testBeanPriorityFromStereotypeOverridesOtherAlternative:54 expected [BazAlternative2] but found [BazAlternative]
[ERROR]   StereotypeWithPriorityTest>Arquillian.run:138->testStereotypeWithAlternativeAndPriority:47 expected [BarExtended] but found [Bar]
[ERROR]   StereotypeWithPriorityTest>Arquillian.run:138->testStereotypeWithPriority:40 expected [FooAlternative] but found [Foo]
[ERROR]   StereotypeInheritedPriorityTest>Arquillian.run:138->testPriorityWasInherited:31 expected [true] but found [false]
[ERROR]   ObserverMethodTest>Arquillian.run:138->testGetDeclaringBeanOnObserverMethod:71 expected object to not be null
[ERROR]   InstanceHandleTest>Arquillian.run:138->testGetAfterDestroyingContextualInstance:96 AbstractMethod
[ERROR]   InstanceHandleTest>Arquillian.run:138->testGetHandle:54 AbstractMethod Receive...
[ERROR]   InstanceHandleTest>Arquillian.run:138->testHandles:120 AbstractMethod Receiver...
[INFO] 
[ERROR] Tests run: 1254, Failures: 14, Errors: 0, Skipped: 6
[INFO] 
[INFO] ------------------------------------------------------------------------
```

**Comment by manovotn** [comment]
Are you sure you have the right version?
When I did a release of Weld 5.0.0.Alpha2, it ran the whole CDI TCK against `4.0.0.Alpha5` (which is the same as RC content-wise) and that passed just fine.

You'd need to give me some details on how you execute it.

**Comment by starksm64** [comment]
I was using an updated local weld core repo. I created a fresh fork and reran with a staging repo profile and all tests are passing:
```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running TestSuite
[INFO] Tests run: 1248, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 94.966 s - in TestSuite
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 1248, Failures: 0, Errors: 0, Skipped: 0
```

**Comment by manovotn** [comment]
Closing this as CR was staged successfully.
